structure:
  diff_name: "ema_cifar10" # Diff name
  clf_log: "cifar10" # Classifier model path
  dataset: "CIFAR10-Un" # Dataset, in [ CIFAR10, CIFAR10-Un]
  bsize: 500 # Batch size
  start_epoch: 0
  end_epoch: 99
  run_samples: 10000

attack:
  if_targeted: false
  attack_method: "clf_pgd" # Attack method: list [clf_pgd, bpda, spsa]
  ptb: 8. # perturbation, pixel scale
  ball_dim: -1 # -1 or 1 or 2
  n_eot: 1 # Number of EOT, 1 if no EOT applied
  attack_lambda: 0.05 # adaptive attack step size strategy
  attack_steps: 10 # Number of attack steps
  iter: 40 # Number of iterations for gradient-based attacks



purification:
  purify_method: "diff_purify" # purification method in [diff_purify]
  max_iter: 4 # Default maximum number of iterations
  path_number: 1 
  purify_step: 20 
  purify_natural: True # Whether to purify natural images, for time complexity

  cond: True # whether to use conditional ` guide 
  condcc: True  # whether to use conditional 2 guide 

  joincond: True # whether to use joint conditional guide  
  join_mode: MSE_LPIPS  # Label_MSE/MSE_LPIPS   finall_mode
  guide_mode: MSE  #'LPIPS' or 'MSE'  
  guide_mode2: LPIPS #'LPIPS' or 'MSE'

  guide_scale: 70000   
  guide_scale_base: 0

device:
  diff_device: "cuda:0"
  clf_device: "cuda:0"
  rank: 0
